### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by CreatorMetaSky** [tripleCC/cocoapods-bin#1]
我有个关于 podspec 解析动态更换 source 的问题，联系方式已经发送到：triplec.linux@gmail.com，这个邮箱了，有时间辛苦加下我，感谢。

**Comment by tripleCC** [comment]
你好，可以在这里说明你的问题

**Comment by CreatorMetaSky** [comment]
@tripleCC  是这样子的，我这边 hook 了 Installer.rb 的 resolve_dependecies 方法，然后根据指定的标记来动态改变，Spec的 s.source 和 s.verndored_frameworks 来实现源码和二进制切换，不知道你用过这种方案吗？

**Comment by tripleCC** [comment]
@CoderAFI  https://github.com/tripleCC/cocoapods-tdfire-binary 这样？只用一个私有源是吧？

**Comment by CreatorMetaSky** [comment]
能加微信聊吗？15210764165

**Comment by CreatorMetaSky** [comment]
@tripleCC 我做的感觉比你要轻量一些，我看了下你是扩展了 Specification  的 DSL，我没有这么实现，我是在 podpsec 里加了一个标记，如果有标记，动态更新 spec.source 和 spec.verndored_frameworks.但是有时候会报 header file not found  的错误，希望请教下你，看你有遇到这种情况吗？

**Comment by tripleCC** [comment]
需要注意下 CocoaPods 的缓存问题。` header file not found` 可能是你 source 变更了，实际并没有去下载变更之后的 source 。个人不建议通过变更一个 podspec 来做依赖切换，做 cocoapods-tdfire-binary 我就遇到了一些这类问题。

**Comment by CreatorMetaSky** [comment]
恩，看了你的代码，对我帮助很大，我也做了动态删除缓存的策略，实际在 xcode 编译都没问题，但是用 cocoapods-packager 有时候就回报 header file not found  问题，还是希望加下微信，深入交流下，如何？
