### ISSUE TITLE
部分pod需要引入二进制

### ISSUE THREAD

**Issue by zhangkboy** [tripleCC/cocoapods-bin#12]
您好:
请问 如果部分pod需要引入二进制的话,podfile里该如何写?

**Comment by tripleCC** [comment]
> 您好:
> 请问 如果部分pod需要引入二进制的话,podfile里该如何写?

如果很多组件都有二进制版本，但是只想引入部分组件的二进制版本：

```ruby
use_binaries_with_spec_selector! do |spec|
  %w[组件名1 组件名2].select { |n| spec.name.start_with?(n) }.empty?
end
```

如果只有想引入的组件有二进制版本：

```ruby
use_binaries!
```
这种情况下，组件没有二进制版本的话，插件会自动切换到源码版本

如果只有极少的组件不用二进制版本，在上面的前提下，配合：

```ruby
use_binaries!
set_use_source_pods %w[组件名1 组件名2]
```

**Comment by njuxjy** [comment]
``` ruby
set_use_source_pods %w[组件名1 组件名2]
```

组件名之间得用逗号分隔下，不然会无效：
``` ruby
set_use_source_pods ['Pod1', 'Pod2']
```

**Comment by tripleCC** [comment]
> ```ruby
> set_use_source_pods
> ```

传入数组就行，`%w[Pod1 Pod2]` 和 `['Pod1', 'Pod2']` 一致
