### ISSUE TITLE
swift pod组件依赖OC三方库 build error

### ISSUE THREAD

**Issue by zhouJinYing** [tripleCC/cocoapods-bin#14]
![image](https://user-images.githubusercontent.com/20291345/68645471-1d497800-0553-11ea-9265-5b8f7c50fe21.png)

请问是否支持Swift? swift依赖了oc三方库，build会出现这种问题，需要进行哪些配置，有解决方案吗？

**Comment by tripleCC** [comment]
没尝试打过 swift 的 static framework，按照错误日志，你添加 `--use-modular-headers ` 试试看

**Comment by tripleCC** [comment]
> 没尝试打过 swift 的 static framework，根据错误日志，你添加 `--use-modular-headers ` 试试看

**Comment by tripleCC** [comment]
> ![image](https://user-images.githubusercontent.com/20291345/68645471-1d497800-0553-11ea-9265-5b8f7c50fe21.png)
> 
> 请问是否支持Swift? swift依赖了oc三方库，build会出现这种问题，需要进行哪些配置，有解决方案吗？

没尝试打过 swift 的 static framework，根据错误日志，你添加` --use-modular-headers` 试试看
