### ISSUE TITLE
package 部分版本报错

### ISSUE THREAD

**Issue by chaiweiwei** [tripleCC/cocoapods-bin#15]
### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.6 (18G1012)
       Xcode : 11.2 (11B52)
         Git : git version 2.12.2
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_2/lib
Repositories : 2dfire-cocoapods-spec - git@git.2dfire.net:ios/cocoapods-spec.git @ 981d9c305fcbfe1e5248a0fe8d5d5c12a1fe4284
               2dfire-cocoapods-spec-binary - git@git.2dfire.net:ios/cocoapods-spec-binary.git @ 19c01cc74aa92d8760328ce982dc08ac7049d460
               2dfire-inc-cocoapods-spec - git@git.2dfire-inc.com:ios/cocoapods-spec.git @ a6f317408a778b5ef0e2dce8c92dd01750cec0f0
               2dfire-ios-cocoapods-spec - http://git.2dfire.net/ios/cocoapods-spec.git @ a1985e3cfd803b597fd4bd61334b05f7de47a2cc
               master - https://github.com/CocoaPods/Specs.git @ d1b443a612ec0223bea47e806f64b576d95a0f3d
```

### Plugins

```
cocoapods-bin                         : 0.1.24
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 1.6.0
cocoapods-open                        : 0.0.8
cocoapods-packager-pro                : 1.5.4
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-tdfire-binary               : 2.0.8
cocoapods-trunk                       : 1.4.1
cocoapods-try                         : 1.1.0
```

### Error

```
NoMethodError - undefined method `available_platforms' for nil:NilClass
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:414:in `validate_platform'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:552:in `add_valid_dependencies_from_node'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:555:in `block in add_valid_dependencies_from_node'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:553:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:553:in

**Comment by tripleCC** [comment]
> ### Stack
> ```
>    CocoaPods : 1.7.5
>         Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
>     RubyGems : 2.7.6
>         Host : Mac OS X 10.14.6 (18G1012)
>        Xcode : 11.2 (11B52)
>          Git : git version 2.12.2
> Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_2/lib
> Repositories : 2dfire-cocoapods-spec - git@git.2dfire.net:ios/cocoapods-spec.git @ 981d9c305fcbfe1e5248a0fe8d5d5c12a1fe4284
>                2dfire-cocoapods-spec-binary - git@git.2dfire.net:ios/cocoapods-spec-binary.git @ 19c01cc74aa92d8760328ce982dc08ac7049d460
>                2dfire-inc-cocoapods-spec - git@git.2dfire-inc.com:ios/cocoapods-spec.git @ a6f317408a778b5ef0e2dce8c92dd01750cec0f0
>                2dfire-ios-cocoapods-spec - http://git.2dfire.net/ios/cocoapods-spec.git @ a1985e3cfd803b597fd4bd61334b05f7de47a2cc
>                master - https://github.com/CocoaPods/Specs.git @ d1b443a612ec0223bea47e806f64b576d95a0f3d
> ```
> 
> ### Plugins
> ```
> cocoapods-bin                         : 0.1.24
> cocoapods-deintegrate                 : 1.0.4
> cocoapods-disable-podfile-validations : 0.1.1
> cocoapods-generate                    : 1.6.0
> cocoapods-open                        : 0.0.8
> cocoapods-packager-pro                : 1.5.4
> cocoapods-plugins                     : 1.0.0
> cocoapods-search                      : 1.0.0
> cocoapods-stats                       : 1.1.0
> cocoapods-tdfire-binary               : 2.0.8
> cocoapods-trunk                       : 1.4.1
> cocoapods-try                         : 1.1.0
> ```
> 
> ### Error
> ```
> NoMethodError - undefined method `available_platforms' for nil:NilClass
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:414:in `validate_platform'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:552:in `add_valid_dependencies_from_node'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:555:in `block in add_valid_dependencies_from_node'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:553:in `each'
> /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:553:in 
> ```

从调用栈上看，是 cocoapods 的问题，可能是内部 podspec 有问题
