### ISSUE TITLE
Archive 二进制包上传

### ISSUE THREAD

**Issue by NicolasKim** [tripleCC/cocoapods-bin#17]
您好我想问一下 archive命令是 打包和上传二进制包到服务器
但是我并没有在archive.rb里看到 上传到服务器的代码
可以指点一下吗

**Comment by tripleCC** [comment]
> 您好我想问一下 archive命令是 打包和上传二进制包到服务器
> 但是我并没有在archive.rb里看到 上传到服务器的代码
> 可以指点一下吗

archive 只是打包，上传服务器需要自己做，想要简单点用 curl 就行。
上传/下载/查询，这个最好自己整理成一系列工具，方便后续你们自己扩展

**Comment by NicolasKim** [comment]
> > 您好我想问一下 archive命令是 打包和上传二进制包到服务器
> > 但是我并没有在archive.rb里看到 上传到服务器的代码
> > 可以指点一下吗
> 
> archive 只是打包，上传服务器需要自己做，想要简单点用 curl 就行。
> 上传/下载/查询，这个最好自己整理成一系列工具，方便后续你们自己扩展

好的 多谢了
