### ISSUE TITLE
如何调试

### ISSUE THREAD

**Issue by NicolasKim** [tripleCC/cocoapods-bin#18]
您好，我想在您写的基础上 加一些功能上去。
现在使用的vscode可以正常调试，但是vscode调试并不是很理想。
所以我想用rubymine进行调试，但是不知道该怎么配置。
请问您是用什么ide做的开发调试工作？

**Comment by tripleCC** [comment]
> 您好，我想在您写的基础上 加一些功能上去。
> 现在使用的vscode可以正常调试，但是vscode调试并不是很理想。
> 所以我想用rubymine进行调试，但是不知道该怎么配置。
> 请问您是用什么ide做的开发调试工作？

我现在都是直接用 sublime 编辑， 在工程下创建sample，然后用命令行直接跑，可以打 log，或者 byebug

**Comment by NicolasKim** [comment]
经过我一晚上的折腾，I've figured it out
