### ISSUE TITLE
如果pod使用podspec的方式，怎么切换到二进制源呢？

### ISSUE THREAD

**Issue by su350380433** [tripleCC/cocoapods-bin#19]
您好，非常感谢您的分享，真是受益匪浅！！！
请问一个，如果通过podspec引用的方式 
pod 'SDWebImage', :podspec => 'https:///Github-iOS/SDWebImage/raw/dev/SDWebImage.podspec'

二进制私有源就没办法找到了，请问在使用podspec的方式下，有什么办法能切换到二进制源码

**Comment by tripleCC** [comment]
> 您好，非常感谢您的分享，真是受益匪浅！！！
> 请问一个，如果通过podspec引用的方式
> pod 'SDWebImage', :podspec => 'https:///Github-iOS/SDWebImage/raw/dev/SDWebImage.podspec'
> 
> 二进制私有源就没办法找到了，请问在使用podspec的方式下，有什么办法能切换到二进制源码

目前插件不支持这种依赖方式的转换

**Comment by su350380433** [comment]
> > 您好，非常感谢您的分享，真是受益匪浅！！！
> > 请问一个，如果通过podspec引用的方式
> > pod 'SDWebImage', :podspec => 'https:///Github-iOS/SDWebImage/raw/dev/SDWebImage.podspec'
> > 二进制私有源就没办法找到了，请问在使用podspec的方式下，有什么办法能切换到二进制源码
> 
> 目前插件不支持这种依赖方式的转换

我们的项目都是依赖于分支开发，从理论上来说，是否能通过修改插件的逻辑，来实现呢？

**Comment by su350380433** [comment]
> 从理论上来说，是否能通过修改插件的逻辑，来实现呢？

您有什么好的思路吗

**Comment by su350380433** [comment]
> > > 您好，非常感谢您的分享，真是受益匪浅！！！
> > > 请问一个，如果通过podspec引用的方式
> > > pod 'SDWebImage', :podspec => 'https:///Github-iOS/SDWebImage/raw/dev/SDWebImage.podspec'
> > > 二进制私有源就没办法找到了，请问在使用podspec的方式下，有什么办法能切换到二进制源码
> > 
> > 
> > 目前插件不支持这种依赖方式的转换
> 
> 我们的项目都是依赖于分支开发，从理论上来说，是否能通过修改插件的逻辑，来实现呢？

您有什么好的思路吗？能否通过拦截地址来修改呢？

**Comment by tripleCC** [comment]
> > > > 您好，非常感谢您的分享，真是受益匪浅！！！
> > > > 请问一个，如果通过podspec引用的方式
> > > > pod 'SDWebImage', :podspec => 'https:///Github-iOS/SDWebImage/raw/dev/SDWebImage.podspec'
> > > > 二进制私有源就没办法找到了，请问在使用podspec的方式下，有什么办法能切换到二进制源码
> > > 
> > > 
> > > 目前插件不支持这种依赖方式的转换
> > 
> > 
> > 我们的项目都是依赖于分支开发，从理论上来说，是否能通过修改插件的逻辑，来实现呢？
> 
> 您有什么好的思路吗？能否通过拦截地址来修改呢？

理论上可以，不过这样可能要自己起一套下载方案，能匹配当前 commit 有对应的静态库。具体没实践过，所以无法给出好的思路

**Comment by su350380433** [comment]
感谢

**Comment by su350380433** [comment]
请问下，一个私有库有多个分支和多个项目依赖，你们是怎么处理的呢？

**Comment by tripleCC** [comment]
> 请问下，一个私有库有多个分支和多个项目依赖，你们是怎么处理的呢？

最终都只会产出一个正式版本，开发时一般建立各自的 feature 分支，开发完成合入 develop，提测起 release ，封板合入 master ，发布正式版本

**Comment by su350380433** [comment]
> > 请问下，一个私有库有多个分支和多个项目依赖，你们是怎么处理的呢？
> 
> 最终都只会产出一个正式版本，开发时一般建立各自的 feature 分支，开发完成合入 develop，提测起 release ，封板合入 master ，发布正式版本

你们是否有遇到过这种场景呢？
项目A，项目B，私有库C

项目A 依赖 私有库C  分支dev_1.0
项目B 依赖 私有库C  分支dev_2.0

这种场景下就不好处理。 这时候的二进制私有源要怎么去切换呢？

**Comment by tripleCC** [comment]
> > > 请问下，一个私有库有多个分支和多个项目依赖，你们是怎么处理的呢？
> > 
> > 
> > 最终都只会产出一个正式版本，开发时一般建立各自的 feature 分支，开发完成合入 develop，提测起 release ，封板合入 master ，发布正式版本
> 
> 你们是否有遇到过这种场景呢？
> 项目A，项目B，私有库C
> 
> 项目A 依赖 私有库C 分支dev_1.0
> 项目B 依赖 私有库C 分支dev_2.0
> 
> 这种场景下就不好处理。 这时候的二进制私有源要怎么去切换呢？

我们只有正式版本才有二进制，分支没有

**Comment by su350380433** [comment]
再次感谢
