### ISSUE TITLE
pod bin repo push --binary 能生成zip包，但有报错

### ISSUE THREAD

**Issue by zhou87** [tripleCC/cocoapods-bin#20]
- ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/unzip /var/folders/w5/b4bk0rpx4dx_stj7dw01461c0000gn/T/d20200305-99987-1ym6st5/file.zip -d /var/folders/w5/b4bk0rpx4dx_stj7dw01461c0000gn/T/d20200305-99987-1ym6st5

Archive:  /var/folders/w5/b4bk0rpx4dx_stj7dw01461c0000gn/T/d20200305-99987-1ym6st5/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/w5/b4bk0rpx4dx_stj7dw01461c0000gn/T/d20200305-99987-1ym6st5/file.zip or
        /var/folders/w5/b4bk0rpx4dx_stj7dw01461c0000gn/T/d20200305-99987-1ym6st5/file.zip.zip, and cannot find /var/folders/w5/b4bk0rpx4dx_stj7dw01461c0000gn/T/d20200305-99987-1ym6st5/file.zip.ZIP, period.
) during validation.

[!] The `flowTestPod.binary.podspec.json` specification does not validate.

**Comment by tripleCC** [comment]
打包出来的 zip 有问题

**Comment by zhou87** [comment]
> 打包出来的 zip 有问题

新建的一个很干净的工程，如果是zip包的问题，可能是我的工程配置的问题吗？

**Comment by tripleCC** [comment]
> > 打包出来的 zip 有问题
> 
> 新建的一个很干净的工程，如果是zip包的问题，可能是我的工程配置的问题吗？

先看打包出来的zip包是否有问题，再看下载过来的zip是否有问题。前者正常，后者不正常，可能下载的服务有问题

**Comment by zhou87** [comment]
> > > 打包出来的 zip 有问题
> > 
> > 
> > 新建的一个很干净的工程，如果是zip包的问题，可能是我的工程配置的问题吗？
> 
> 先看打包出来的zip包是否有问题，再看下载过来的zip是否有问题。前者正常，后者不正常，可能下载的服务有问题

那很有可能是服务的问题了，我本地起的binary-server，貌似每次都没有上传上传成功，服务器只调用到了frameworks的get请求。所以很奇怪为什么为会报unzip的错误，看了里面的实现逻辑应该是`push.validate!`这里面报的错，这里应该是调用cocoapods的校验方法。关键是我现在好像还没有找到上传zip包的代码在哪，很尴尬😅

**Comment by zhou87** [comment]
> > > 打包出来的 zip 有问题
> > 
> > 
> > 新建的一个很干净的工程，如果是zip包的问题，可能是我的工程配置的问题吗？
> 
> 先看打包出来的zip包是否有问题，再看下载过来的zip是否有问题。前者正常，后者不正常，可能下载的服务有问题

`pod bin archive` 能正常打出zip包，但是`pod bin repo push` 的时候没能打出`zip`包，直接报这个错，那应该是`repo push`这个命令打包出了问题。

**Comment by tripleCC** [comment]
> > > > 打包出来的 zip 有问题
> > > 
> > > 
> > > 新建的一个很干净的工程，如果是zip包的问题，可能是我的工程配置的问题吗？
> > 
> > 
> > 先看打包出来的zip包是否有问题，再看下载过来的zip是否有问题。前者正常，后者不正常，可能下载的服务有问题
> 
> `pod bin archive` 能正常打出zip包，但是`pod bin repo push` 的时候没能打出`zip`包，直接报这个错，那应该是`repo push`这个命令打包出了问题。

有把 zip 包上传到静态文件服务器么，直接拿到这个 zip 包的下载链接试试，加 --no-clean  会保留生成的二进制 podspec ，把 source 里面的链接拿出来试试就行

**Comment by zhou87** [comment]
> > > > > 打包出来的 zip 有问题
> > > > 
> > > > 
> > > > 新建的一个很干净的工程，如果是zip包的问题，可能是我的工程配置的问题吗？
> > > 
> > > 
> > > 先看打包出来的zip包是否有问题，再看下载过来的zip是否有问题。前者正常，后者不正常，可能下载的服务有问题
> > 
> > 
> > `pod bin archive` 能正常打出zip包，但是`pod bin repo push` 的时候没能打出`zip`包，直接报这个错，那应该是`repo push`这个命令打包出了问题。
> 
> 有把 zip 包上传到静态文件服务器么，直接拿到这个 zip 包的下载链接试试，加 --no-clean 会保留生成的二进制 podspec ，把 source 里面的链接拿出来试试就行

找到原因了，bin.yaml配置的binary_download_urlbinary_download_url有问题，下载地址最后面是`/zip`而不是`.zip`，怪不得总是会调用show方法，download方法是不走的。
