### ISSUE TITLE
打成静态包的时候source_file路径不对

### ISSUE THREAD

**Issue by zhou87** [tripleCC/cocoapods-bin#23]
报错信息：
       file patterns: The `source_files` pattern did not match any file

   目录下面所有的"Headers"文件夹下面的文件都为空，应该是在拷贝source_file的时候没有找到对应的文件，跟我的工程配置有关。
有很多东西想跟大佬请教下，可以加个微信么：18868825142

**Comment by LoveLifeLoveSelf** [comment]
问题解决了吗？
