### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by zhou87** [tripleCC/cocoapods-bin#25]
A、B两个Pod，A以二进制的方式引入项目，B以源码的方式引入，B依赖A，引用A中文件#import <A/A.h>时会报这个错，找不到A的定义。查了很久，感觉应该是路径问题，在search path里面也都加了路径，一直是这个报错，之前有遇到过吗？

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_A_class1", referenced from:
      objc-class-ref in B_class.o
  "_OBJC_CLASS_$_A_class2", referenced from:
      objc-class-ref in B_class.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tripleCC** [comment]
> A、B两个Pod，A以二进制的方式引入项目，B以源码的方式引入，B依赖A，引用A中文件#import <A/A.h>时会报这个错，找不到A的定义。查了很久，感觉应该是路径问题，在search path里面也都加了路径，一直是这个报错，之前有遇到过吗？
> 
> Undefined symbols for architecture x86_64:
> "_OBJC_CLASS_$_A_class1", referenced from:
> objc-class-ref in B_class.o
> "_OBJC_CLASS_$_A_class2", referenced from:
> objc-class-ref in B_class.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

这个是链接阶段找不到符号，和 search path 无关，search path 有问题会在编译阶段报错，静态库是否缺少 x86_64 架构

**Comment by zhou87** [comment]
> > A、B两个Pod，A以二进制的方式引入项目，B以源码的方式引入，B依赖A，引用A中文件#import <A/A.h>时会报这个错，找不到A的定义。查了很久，感觉应该是路径问题，在search path里面也都加了路径，一直是这个报错，之前有遇到过吗？
> > Undefined symbols for architecture x86_64:
> > "_OBJC_CLASS_$_A_class1", referenced from:
> > objc-class-ref in B_class.o
> > "_OBJC_CLASS_$_A_class2", referenced from:
> > objc-class-ref in B_class.o
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> 这个是链接阶段找不到符号，和 search path 无关，search path 有问题会在编译阶段报错，静态库是否缺少 x86_64 架构

用lipo命令查看是支持x86_64架构：
 lipo -info A
Architectures in the fat file: A are: armv7 armv7s i386 x86_64 arm64

在stackoverflow上看确实有一些解决方案是通过拖入静态库到主项目的方式解决，所以怀疑我项目里面可能也是路径问题。在查看报错日志的时候，确实发现xcode在找这个静态库的时候路径跟其他的pod是有区别的：
![image](https://user-images.githubusercontent.com/12960002/77714193-65090180-7013-11ea-8f42-0afa8cc8be91.png)
不知道你们在配置的时候有没有遇到过这样的问题？

**Comment by zhou87** [comment]
> > A、B两个Pod，A以二进制的方式引入项目，B以源码的方式引入，B依赖A，引用A中文件#import <A/A.h>时会报这个错，找不到A的定义。查了很久，感觉应该是路径问题，在search path里面也都加了路径，一直是这个报错，之前有遇到过吗？
> > Undefined symbols for architecture x86_64:
> > "_OBJC_CLASS_$_A_class1", referenced from:
> > objc-class-ref in B_class.o
> > "_OBJC_CLASS_$_A_class2", referenced from:
> > objc-class-ref in B_class.o
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> 这个是链接阶段找不到符号，和 search path 无关，search path 有问题会在编译阶段报错，静态库是否缺少 x86_64 架构

-F/Users/xxx/Library/Developer/Xcode/DerivedData/ProjectName-cxybyifawxhjzmeexbbxvtqxasjc/Build/Products/Debug-iphonesimulator/SVProgressHUD 
-F/Users/xxxx/Library/Developer/Xcode/DerivedData/ProjectName-cxybyifawxhjzmeexbbxvtqxasjc/Build/Products/Debug-iphonesimulator/Yoga 
-F/Users/xxxx/Library/Developer/Xcode/DerivedData/ProjectName-cxybyifawxhjzmeexbbxvtqxasjc/Build/Products/Debug-iphonesimulator/ZipArchive 
-F/Users/xxxx/Documents/iOS项目/ProjectName/Pods/SCCPhotoBrowser

图片加载不出来，贴几个路径。最后这个是静态库的路径，错误日志上好像只有这里有点区别，这个不知道是不是一个排查的方向，之前尝试过将search path 改成跟其他的pod路径一致，但好像并没有什么效果...
