### ISSUE TITLE
有subspec的组件，提供的模板怎么写呢

### ISSUE THREAD

**Issue by zhou87** [tripleCC/cocoapods-bin#27]
如果有`subspec`的组件在生成二进制的时候模板改怎么写呢？就拿`readme`中的例子，`A.binary-template.podspec`应该长啥样子？尝试几次都没有打包成功...

我想把项目中所有依赖`github`上的三方组件都打成二进制，比如`AFNetworking`、`SDWebImage`、`RxSwift`这些，理论上最好是放在自己的私有源上对吧，你们团队现在的做法也是这样吗？

**Comment by tripleCC** [comment]
> 如果有`subspec`的组件在生成二进制的时候模板改怎么写呢？就拿`readme`中的例子，`A.binary-template.podspec`应该长啥样子？尝试几次都没有打包成功...
> 
> 我想把项目中所有依赖`github`上的三方组件都打成二进制，比如`AFNetworking`、`SDWebImage`、`RxSwift`这些，理论上最好是放在自己的私有源上对吧，你们团队现在的做法也是这样吗？

README 里面 https://github.com/tripleCC/cocoapods-bin#%E4%BA%8C%E8%BF%9B%E5%88%B6-podspec 有。

是都放在私有源，不依赖外部源

**Comment by zhou87** [comment]
谢谢
