### ISSUE TITLE
组件pod bin archive找不到私有源

### ISSUE THREAD

**Issue by LoveLifeLoveSelf** [tripleCC/cocoapods-bin#31]
localhost% pod bin archive XXXNetwork.podspec

[!] Unable to find a specification for `AFNetworking (= 3.2.1)` depended upon by `ZPMNetwork`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

XXXNetWork里面有两个依赖库，来自两个不同私有源，如何设置才能打zip包成功

**Comment by tripleCC** [comment]
> localhost% pod bin archive XXXNetwork.podspec
> 
> [!] Unable to find a specification for `AFNetworking (= 3.2.1)` depended upon by `ZPMNetwork`
> 
> You have either:
> 
> * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.
> 
> XXXNetWork里面有两个依赖库，来自两个不同私有源，如何设置才能打zip包成功

尝试过 --sources 么

**Comment by LoveLifeLoveSelf** [comment]
> > localhost% pod bin archive XXXNetwork.podspec
> > [!] Unable to find a specification for `AFNetworking (= 3.2.1)` depended upon by `ZPMNetwork`
> > You have either:
> > 
> > * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> > * mistyped the name or version.
> > * not added the source repo that hosts the Podspec to your Podfile.
> > 
> > XXXNetWork里面有两个依赖库，来自两个不同私有源，如何设置才能打zip包成功
> 
> 尝试过 --sources 么

尝试了下，通过了，谢谢
