### ISSUE TITLE
include of non-modular header inside framework module

### ISSUE THREAD

**Issue by diegoeddy** [tripleCC/cocoapods-bin#35]
工程中有几个Pod设置成源码依赖，其他Pod走二进制

use_binaries!
set_use_source_pods ['PFLUtils']

有一个Pod名字叫PFLAppframwork，使用二进制，它依赖PFLUtils这个库。PFLUtils用的是源码

pod install之后，编译报错

include of non-modular header inside framework module 'PFLAppframework.XCListModel': 'Pods/Headers/Private/PFLUtils/PUtils.h'

工程中设置Allow Non-modular Includes In Framework Modules 为 YES无效

**Comment by tripleCC** [comment]
参考：https://github.com/tripleCC/cocoapods-bin/issues/16#issuecomment-576091813

**Comment by diegoeddy** [comment]
我用的是伞头文件的方式。但还是不行

<img width="1326" alt="截屏2020-07-21 下午5 35 40" src="https://user-images.githubusercontent.com/4538404/88038481-dc414300-cb78-11ea-87b4-21523ab7a69d.png">

**Comment by tripleCC** [comment]
参考这个 issue：https://github.com/CocoaPods/CocoaPods/issues/8668 ，插件没做适配

**Comment by diegoeddy** [comment]
modulemap文件我也加了,也不行

          framework module PFLUtils {
            umbrella header "PUtils.h"

            export *
            module * { export * }
          }

是不是二进制组件无法直接依赖源码组件？

**Comment by tripleCC** [comment]
可以以来源码组件。不过当时我还是 1.7.x 版本的，不清楚新版本是否更严格了。

不行的话，可以把头文件放 .m

**Comment by diegoeddy** [comment]
经过尝试，在Podfile里增加use_modular_header!可以解决。但同时需要在源码Pod中增加module.modulemap文件
