### ISSUE TITLE
set_use_source_pods ['YYModel']不生效

### ISSUE THREAD

**Issue by YaoJuan** [tripleCC/cocoapods-bin#38]
use_binaries!
 set_use_source_pods ['YYModel']
yymodel依旧是二进制版本。。而且感觉对应的几个use_binaries_with_spec_selector都无法生效

**Comment by tripleCC** [comment]
> use_binaries!
> set_use_source_pods ['YYModel']
> yymodel依旧是二进制版本。。而且感觉对应的几个use_binaries_with_spec_selector都无法生效

这个库暂时不维护了，推荐使用 https://github.com/MeetYouDevs/cocoapods-imy-bin
