### ISSUE TITLE
podspec有依赖其他组件不成功啊

### ISSUE THREAD

**Issue by zhangkboy** [tripleCC/cocoapods-bin#4]
podspec有依赖其他组件 pod bin spec lint 不成功啊
pod bin spec lint --sources= 也不成功
这是什么情况

**Comment by tripleCC** [comment]
提示什么日志呢？
最好能把示例工程发下

**Comment by zhangkboy** [comment]
工程有些大
我podspec里有依赖github的也有依赖私有的pod
这是报错：
### Error

```
TypeError - no implicit conversion of String into Array
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/helpers/sources_helper.rb:28:in `sources_option'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/command/bin/spec/lint.rb:48:in `block (3 levels) in run'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/native/podfile_env.rb:26:in `execute_with_key'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/native/podfile_env.rb:19:in `execute_with_use_binaries'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/command/bin/spec/lint.rb:46:in `block (2 levels) in run'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/native/podfile_env.rb:26:in `execute_with_key'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/native/podfile_env.rb:15:in `execute_with_allow_prerelease'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/command/bin/spec/lint.rb:45:in `block in run'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/native/podfile_env.rb:26:in `execute_with_key'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/native/podfile_env.rb:11:in `execute_with_bin_plugin'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-bin-0.1.15/lib/cocoapods-bin/command/bin/spec/lint.rb:44:in `run'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Users/zhangkaichao/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by zhangkboy** [comment]
这是我的命令
pod bin spec lint WYAccount.binary.podspec.json --sources=git@192.168.1.78:iOSTeam/ALSpecs.git,https://github.com/CocoaPods/Specs.git --allow-warnings --use-libraries

**Comment by tripleCC** [comment]
更新下版本试试，是一个 bug

如果要做二进制，建议最好把 github 里面的库都整到私有源，这样快点

**Comment by zhangkboy** [comment]
lint的时候报这个错，这个怎么解决：
    - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `resources` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `public_header_files` pattern did not match any file.

这个是podspec：
"resources": [
    "APod.framework/Resources/*.bundle",
    "APod.framework/Versions/A/Resources/*.bundle"
  ],
  "source_files": [
    "APod.framework/Headers/*",
    "APod.framework/Versions/A/Headers/*"
  ],
  "public_header_files": [
    "APod.framework/Headers/*",
    "APod.framework/Versions/A/Headers/*"
  ],

**Comment by tripleCC** [comment]
APod 有头文件么？

还有 framework压缩时不要有中间层级，直接压缩 APod.framework

**Comment by Yanyuxxxx** [comment]
lint 的时候报错，请问一下是什么原因

pod bin spec lint --binary YUTableLayoutView.binary.podspec.json --sources=https://github.com/CocoaPods/Specs.git --allow-warnings

[!] The specification of arguments as a string has been deprecated Pod::Command::Githooks: `NAME`

 -> YUTableLayoutView (0.0.2)
    - WARN  | description: The description is equal to the summary.
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/unzip /var/folders/0v/hy56km7n67vfhpwgp1nyctrm0000gn/T/d20200422-26253-1xetwvw/file.zip -d /var/folders/0v/hy56km7n67vfhpwgp1nyctrm0000gn/T/d20200422-26253-1xetwvw

Archive:  /var/folders/0v/hy56km7n67vfhpwgp1nyctrm0000gn/T/d20200422-26253-1xetwvw/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/0v/hy56km7n67vfhpwgp1nyctrm0000gn/T/d20200422-26253-1xetwvw/file.zip or
        /var/folders/0v/hy56km7n67vfhpwgp1nyctrm0000gn/T/d20200422-26253-1xetwvw/file.zip.zip, and cannot find /var/folders/0v/hy56km7n67vfhpwgp1nyctrm0000gn/T/d20200422-26253-1xetwvw/file.zip.ZIP, period.
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
