### ISSUE TITLE
升级到大于等于1.7.0的cocoapod之后报错

### ISSUE THREAD

**Issue by taozaizai** [tripleCC/cocoapods-bin#5]
执行pod install报错,use_binaries_with_spec_selector!
NameError - undefined local variable or method `installation_options' for #<Pod::Resolver:0x00007fd52ac64718>

**Comment by tripleCC** [comment]
适配了下
可以试下 0.1.17 版本

**Comment by taozaizai** [comment]
又出现了一个新的问题,我切成源码方式发现我的subspec少了几个,去掉podfile的plugin就正常了,走源码方式的应该跟原来保持一致才是吧,我看你改了subspec那里的一些代码

**Comment by tripleCC** [comment]
能贴下 use_binaries_with_spec_selector! 的内容么？
上面只做了兼容，没有逻辑上的变更。你有试过 1.7.0 以下的版本么，在你的工程上是否可行？
