### ISSUE TITLE
use_binaries_with_spec_selector 只有一个有效

### ISSUE THREAD

**Issue by zhangkboy** [tripleCC/cocoapods-bin#7]
测了好几次，use_binaries_with_spec_selector里面只有最后一个有效；

**Comment by tripleCC** [comment]
是有多个 use_binaries_with_spec_selector 语句么？这个内部只是设置了一个属性，如果多次设置，保留最后一次操作结果。一般很少会用到这个，set_use_source_pods 基本满足日常要求了
