### ISSUE TITLE
pod 'MtUIKit',:path=>'./MtUIKit'。这种本地的组件（无远程仓库对应）支持吗？

### ISSUE THREAD

**Issue by zhangjianbin** [tripleCC/cocoapods-bin#8]

**Comment by tripleCC** [comment]
不支持
插件只有在组件存在正式版本的情况下，才会切换依赖

**Comment by zhangjianbin** [comment]
您提供的这个插件中怎么生成对应的二进制文件呢？需要自己去实现还是插件提供实现方式。我没看到插件提供相关命令。

**Comment by tripleCC** [comment]
插件只提供了切换 / 校验 / 发布 podspec 的相关工具链，二进制文件需要自己打，README 中有相关说明

**Comment by zhangjianbin** [comment]
好的，期待插件提供二进制的实现，貌似目前无论pod package 还是Rome都需要更改插件才能达到生成对应三方库的二进制的效果。
