### ISSUE TITLE
有subspec的情况下无法拉取二进制

### ISSUE THREAD

**Issue by allenGit3824** [tripleCC/cocoapods-bin#9]

**Comment by allenGit3824** [comment]
二进制和源码同时存在，并且有subspec的情况下，指定拉二进制无法生效，只能拉到源码

**Comment by tripleCC** [comment]
你的二进制 podspec.template 能看下么？
pod bin lib lint --binary 是否成功？

**Comment by allenGit3824** [comment]
> 你的二进制 podspec.template 能看下么？
> pod bin lib lint --binary 是否成功？

是这样的，二进制是我们自己用工具打的，然后放ftp上，二进制的podspec不区分subspec，都是一样的格式，不同版本只修改下版本号
```
s.ios.vendored_frameworks = "#{s.name}.framework"
  s.source_files = "#{s.name}.framework/Headers/*"
  s.public_header_files = "#{s.name}.framework/Headers/*"
```

然后通过cocoapods-bin来切换。 如果一个版本，只有二进制，那是没问题的，可以正常拉下来。 如果同时有源码和二进制，没有subspec的情况下也是能正常切换的。 但如果源码的podspec有subspec，切换就有问题了

**Comment by allenGit3824** [comment]
调了下，是我自己的疏忽，打好了framework，但是没有把对应版本的二进制podspec上传，导致
specification = source.specification(rspec.root.name, spec_version) 
这句找不到对应的spec
